<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="{{ asset('/css/app.css') }}" rel="stylesheet"> 
    <title>Main page</title>


</head>

<body class="bg-light">
    <header class="p-2 text-white bg-dark fixed-top">
        <div class="container-fluid">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-controller" viewBox="0 0 16 16">
                        <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1v-1z" />
                        <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729c.14.09.266.19.373.297.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466.206.875.34 1.78.364 2.606.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527-1.627 0-2.496.723-3.224 1.527-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.34 2.34 0 0 1 .433-.335.504.504 0 0 1-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a13.748 13.748 0 0 0-.748 2.295 12.351 12.351 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.354 12.354 0 0 0-.339-2.406 13.753 13.753 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27-1.036 0-2.063.091-2.913.27z" />
                    </svg>
                </a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-1 justify-content-center mb-md-0">
                    <li><a href="#" class="nav-link px-2 text-white">Home</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">About</a></li>
                </ul>

                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2">Login</button>
                    <button type="button" class="btn btn-outline-light">Sign-up</button>
                </div>
            </div>
        </div>
    </header>
    <main class="flex-shrink-0">
        <div class="container-fluid mt-5 p-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a consectetur ipsum. Vestibulum sed augue odio. Ut id odio orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec ligula justo, semper vel laoreet ut, venenatis ut elit. Aenean viverra diam a odio consectetur condimentum. Etiam mollis accumsan lectus a interdum. Cras ex magna, varius faucibus auctor mattis, convallis non turpis. Curabitur vulputate dui a mi sagittis, eget sodales elit condimentum. Morbi sagittis cursus hendrerit. Fusce libero massa, elementum vel enim at, laoreet laoreet leo. Duis nec metus fermentum, tempor dolor a, tincidunt ex. Nunc pretium lobortis erat, id tempus lorem viverra eget. Nullam ultricies vulputate magna, vitae scelerisque turpis accumsan a. Proin aliquam at sapien ac tincidunt.

Pellentesque ut aliquet urna, eu bibendum arcu. Maecenas elementum tortor vel fringilla sagittis. Fusce ante dui, congue non pretium eget, maximus eu eros. Donec pulvinar est sapien. Aliquam lobortis lectus et ligula placerat vestibulum. Nulla ut purus a lorem sagittis faucibus. Nunc varius auctor enim et efficitur.

Integer auctor arcu et metus suscipit, ac feugiat erat aliquam. Fusce hendrerit congue tincidunt. Fusce laoreet orci vel faucibus porttitor. Vestibulum metus erat, condimentum sit amet elementum id, laoreet sed libero. Vestibulum fermentum at nulla sed sollicitudin. Curabitur lobortis tempor venenatis. Praesent non leo erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras eget felis nisi. Curabitur elit ligula, iaculis rhoncus consequat in, convallis id sapien.

Donec mattis lectus eget libero volutpat, non porta neque accumsan. Aenean tincidunt nisi sapien, sed aliquam lectus congue vel. Nunc tincidunt nibh diam, at eleifend risus mollis vel. Proin mauris odio, aliquam euismod odio sit amet, tincidunt congue augue. Donec egestas tellus diam, vel placerat libero ultrices ac. Vestibulum id auctor velit, id ultricies orci. Sed in metus eu ante accumsan tempor. Vivamus in quam lectus. Etiam sed nisi nibh.

Aliquam convallis rhoncus ultricies. Suspendisse interdum nisl cursus, mollis sem nec, sagittis dui. Phasellus bibendum massa vitae tellus molestie commodo. Vestibulum tincidunt dui quam, ut ultrices ante aliquam eu. Sed rutrum diam justo, non lacinia eros vestibulum sit amet. Nulla tincidunt vehicula massa eu sodales. Aliquam ipsum sapien, ultrices et elit vulputate, tristique varius urna. Praesent vestibulum lorem id enim vestibulum auctor. Integer pharetra vitae metus a ultrices. Fusce eu velit varius, commodo arcu sit amet, volutpat nibh. Donec velit ex, facilisis quis diam in, finibus ornare mauris. Proin laoreet auctor eros, vitae dictum diam lacinia quis.

Donec laoreet iaculis turpis eu mattis. Phasellus varius auctor nisi a ornare. Fusce et velit sed odio auctor egestas. Proin tempor ipsum et leo semper, et tincidunt nibh blandit. Aenean tempus quis turpis at mattis. Pellentesque quis rutrum purus. Aenean bibendum rhoncus mi vel semper. Sed ac massa lorem. Nulla vitae dictum metus. Cras non ligula vitae odio volutpat mattis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla nec sem in diam eleifend blandit sit amet et mi. Etiam ac pulvinar orci, vitae dictum diam. In faucibus velit neque, et finibus leo tristique vel. Pellentesque ut arcu metus.

Fusce ex lacus, luctus non venenatis vel, condimentum eget tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel nisl efficitur, vestibulum diam ut, gravida odio. Suspendisse congue efficitur maximus. Nam commodo ut ex vitae cursus. Morbi tempus ornare metus, nec elementum neque dignissim sed. Mauris sagittis ultrices ex, nec porttitor risus luctus eget. Sed non risus nunc. Donec sed nibh sapien. Fusce quam ex, luctus vel fringilla quis, hendrerit non nunc. Ut varius aliquet arcu auctor gravida. Praesent eu velit nec ligula porttitor aliquet eget nec magna. Donec ligula enim, facilisis ac vestibulum quis, ornare in purus.

Vestibulum odio velit, feugiat a tincidunt elementum, pharetra sit amet dui. Suspendisse potenti. Nam rhoncus metus auctor semper lobortis. Donec egestas porttitor odio, ac faucibus felis gravida nec. Vivamus tincidunt sollicitudin metus vitae lobortis. Integer et ultrices enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla nisi neque, vehicula eget luctus et, sollicitudin sed dolor. Mauris ornare ipsum sed pharetra cursus. Suspendisse ut pulvinar lectus.

Praesent rhoncus tempor nisl. Sed malesuada euismod faucibus. Ut aliquam erat nulla. Aenean id laoreet lacus. Curabitur tincidunt, dui quis posuere sagittis, purus libero imperdiet magna, eleifend imperdiet lorem tellus a elit. Phasellus condimentum in urna id condimentum. Donec maximus, lacus nec molestie ullamcorper, metus nulla ullamcorper nibh, et efficitur metus enim at mi. Curabitur pretium lectus eget ligula rhoncus dignissim. Sed molestie id velit nec blandit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non massa in urna volutpat aliquet in nec elit. Sed velit velit, fermentum ut orci sit amet, ornare rhoncus enim.

Pellentesque fringilla metus orci, vel cursus urna iaculis luctus. Proin pharetra neque id mi eleifend, ac consequat neque venenatis. Nam efficitur id tellus vitae gravida. Morbi dictum vel risus ut tristique. Donec nec diam rhoncus, porttitor mauris vitae, bibendum libero. Vestibulum at iaculis tortor. Donec est velit, dapibus non risus iaculis, consequat ullamcorper enim. Vivamus diam neque, tempus aliquam tellus vitae, blandit congue justo. Vestibulum viverra in lacus vel lacinia. Nullam id ornare mauris.

In rhoncus leo at tempus efficitur. Ut quam magna, facilisis at lectus eget, egestas imperdiet lacus. Maecenas efficitur est sit amet enim placerat, in lobortis lacus dapibus. In a lectus pretium, viverra odio non, imperdiet felis. Ut placerat tincidunt elit, sed sagittis nisl mollis sit amet. Sed tellus ligula, facilisis in libero egestas, maximus aliquam sapien. Phasellus justo arcu, sagittis sit amet mauris quis, interdum sagittis metus. Duis quis tellus dolor. Morbi pellentesque, eros vel egestas efficitur, est nulla scelerisque elit, non varius massa nunc in quam. Aenean elit magna, lobortis in augue eget, fringilla euismod dui. Mauris sit amet nisl sem. Aliquam mollis venenatis cursus. Aenean a est dolor. Curabitur a mauris nunc. Vestibulum eleifend non urna eget ultricies. Mauris ut enim a mauris ultricies commodo.

Sed sed massa lectus. Donec ac scelerisque dolor. Vestibulum scelerisque tempus venenatis. Etiam mollis libero maximus dolor consectetur vestibulum. Nulla facilisi. Aenean ac est et justo porta fermentum congue id tellus. Donec quis aliquam nisl, et aliquet felis. Mauris aliquet ultricies aliquam. Integer dapibus, arcu eget ultricies luctus, sem metus mollis augue, at volutpat ipsum risus sit amet nisi.

Aliquam non sapien malesuada, gravida urna non, pellentesque ligula. Donec semper lacus at lacus commodo dapibus. In sed egestas lectus, id aliquet leo. Aliquam quis aliquet velit. In id diam ac mauris congue mattis vel in ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec at urna ligula. Suspendisse lacinia, lorem vel suscipit maximus, leo lectus rhoncus orci, eu consequat metus ipsum eget dui. Ut facilisis nisl vitae volutpat posuere. Quisque vel ornare tellus, nec eleifend urna. Vivamus ligula sapien, lacinia ut mi non, eleifend tincidunt ipsum. Duis finibus nibh arcu.

Quisque accumsan elementum iaculis. Quisque pretium, nulla vitae mattis rhoncus, ipsum dolor luctus mi, in rhoncus turpis quam sit amet nisl. Quisque a quam nec metus viverra semper vel eget nulla. Pellentesque convallis mollis enim, ut commodo neque maximus non. Suspendisse orci nulla, placerat eu massa vitae, auctor bibendum erat. In venenatis pretium neque id consectetur. Mauris ut magna sit amet nulla iaculis vulputate. Ut lorem mi, molestie vitae porta eu, malesuada a nisi. In sit amet est sed odio ultricies pellentesque. Vivamus eu dui et eros malesuada tempus.

Vestibulum et auctor dolor, quis vestibulum justo. Mauris imperdiet ut felis et lobortis. Sed rutrum tellus in turpis porta pellentesque. Maecenas aliquam egestas urna non tempus. Donec elementum ultricies scelerisque. Quisque fringilla nec quam nec rhoncus. Curabitur ac nulla non libero luctus rutrum vel quis ipsum. Nulla odio leo, suscipit sit amet tempus a, gravida sit amet nisi.

Cras fringilla nulla metus, eget mattis mauris pellentesque nec. In aliquet non elit at vestibulum. Duis rhoncus cursus massa, a suscipit ante scelerisque sit amet. Integer ut ultrices urna. Ut convallis quis sem non mattis. Fusce vel leo elit. Proin tristique diam ac erat pretium sagittis. Praesent ut molestie quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed gravida, est non rutrum luctus, lectus ante mattis massa, sit amet euismod nisl quam posuere erat. Donec tincidunt eu elit sed consequat. Nullam in mi ac enim dignissim hendrerit. Maecenas malesuada leo sem, vitae gravida enim bibendum non. Aenean quis elementum nisl.

Aenean nisi leo, cursus vitae velit sed, iaculis lacinia lacus. In euismod blandit tellus ac semper. Morbi lacus nunc, auctor eget feugiat in, tincidunt ut nunc. Vestibulum venenatis elit eget purus varius convallis. Aenean sed hendrerit arcu. Quisque vel euismod ligula, blandit lacinia dui. Ut id maximus sapien. Nam iaculis tempus tortor, eget venenatis metus volutpat quis. Donec scelerisque, metus at venenatis dictum, diam nunc ultricies dolor, ut ornare mauris lorem sed felis. Integer id dui vitae tellus tempus dapibus. Donec pharetra arcu vel odio tempus, eget lobortis risus malesuada.

Sed gravida convallis consequat. Sed id libero tortor. Pellentesque at imperdiet arcu, sit amet finibus urna. Morbi a justo eget urna congue elementum. Suspendisse et lorem sem. Vivamus commodo vel nibh sit amet finibus. Phasellus bibendum vulputate augue et feugiat. Sed tempor ex sed justo posuere egestas. Vestibulum eget maximus nibh. Sed gravida dictum sagittis. Quisque condimentum nibh non augue convallis, a suscipit libero interdum. Sed iaculis augue enim. Phasellus sed massa eget ligula tempor facilisis a ac felis.

Sed ullamcorper ante eget dolor viverra ullamcorper. Phasellus a ex auctor, euismod felis non, tristique ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque feugiat urna vitae odio iaculis luctus. Mauris tempus non massa ac tincidunt. Vivamus ipsum orci, vehicula at leo ac, aliquet dignissim elit. Praesent rutrum justo vitae lacus lobortis, at tincidunt lacus auctor. Nullam faucibus sapien at ipsum auctor suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ac nibh eu augue sodales vestibulum vel in felis. Integer varius ut justo id facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vel ipsum libero. Etiam sed ipsum lorem. Nulla felis lorem, aliquet sit amet eleifend in, iaculis sit amet orci. Sed ante ligula, posuere ac orci a, ornare semper felis. Suspendisse dignissim ac odio eget scelerisque. Praesent orci felis, suscipit sed lobortis pulvinar, dictum vitae lorem. Donec consectetur aliquam cursus. Nunc id mollis mauris. Phasellus tellus velit, vulputate ac scelerisque quis, porttitor at ex. In et ipsum egestas, mollis elit a, volutpat augue. Quisque pretium tellus non efficitur gravida. Sed in metus quis ante varius ornare a in augue.

Maecenas at est eu massa venenatis maximus. Cras nisl diam, tempus iaculis urna sit amet, auctor interdum nibh. Morbi eros dolor, faucibus eu vulputate sit amet, faucibus non ante. Nam consequat libero in eleifend imperdiet. Vivamus elementum ac urna in dictum. Donec venenatis leo in placerat finibus. Donec scelerisque diam eu eleifend ornare. Integer rhoncus ornare pharetra. Vestibulum ut augue dolor. Cras dapibus justo hendrerit justo lobortis scelerisque.

Nulla eleifend eleifend massa id accumsan. Duis blandit, urna posuere pulvinar rutrum, dolor purus scelerisque ex, eu feugiat turpis augue eu nunc. Pellentesque ut semper turpis. Donec justo velit, sodales eget auctor vel, porta sit amet dolor. Fusce vitae tristique nisl, vitae volutpat leo. Aliquam interdum magna eu quam mattis fermentum. Cras bibendum nibh metus, sed malesuada libero finibus et. Mauris enim nibh, varius ultricies tortor quis, fermentum volutpat quam. Nullam laoreet eros et urna tincidunt, a sodales quam tincidunt. Etiam ultrices elit vel rutrum sollicitudin. Phasellus id nisi purus.

Nullam et tellus quis odio volutpat cursus ac ut libero. Integer a tincidunt mi, vitae scelerisque elit. Vestibulum ipsum enim, convallis vel consequat vestibulum, cursus a nisl. In fermentum metus vel dolor convallis tempor. In hac habitasse platea dictumst. Phasellus nisi nibh, imperdiet et ultricies quis, sodales ac sapien. Mauris vel velit non risus consectetur porta sed sit amet justo. Cras et dolor et erat tincidunt efficitur. Nulla facilisi. Donec iaculis, turpis eu consequat rutrum, libero felis cursus nibh, interdum euismod lorem neque quis risus. Pellentesque nec orci quis ex commodo convallis. In semper eleifend tellus a elementum. Phasellus tortor felis, pellentesque in suscipit at, fermentum et enim. Morbi nulla nunc, suscipit vitae elit in, fringilla vestibulum dolor. Vivamus eu ligula consequat, lobortis lectus et, placerat diam. Integer tempus pharetra nulla, a rutrum ipsum tempus quis.

Nulla a tempus nulla. Praesent fermentum ligula ut dolor mattis iaculis. Maecenas et tellus congue, vestibulum nisl non, blandit augue. Nulla fermentum condimentum velit. In dui nisi, dignissim quis ipsum vitae, iaculis sagittis justo. Praesent accumsan est et magna dapibus, a tempus erat congue. Aliquam tristique tellus quis ligula accumsan, quis tempus nunc lobortis. Donec sit amet sem eget diam tincidunt rutrum nec a nunc. Vivamus eget metus ut mauris feugiat tristique id at turpis.

In sit amet viverra augue. Sed commodo dictum libero quis convallis. Mauris aliquet libero vel mi sodales, non sodales augue malesuada. Vestibulum porta, elit et vehicula tempus, augue nunc ornare libero, id ornare risus erat non risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut egestas turpis, sit amet egestas nibh. Nullam sollicitudin posuere lacus vel pulvinar. Pellentesque vel metus bibendum, tristique magna sed, porttitor mauris. Phasellus at dolor at leo blandit vestibulum tempor vel purus. Praesent ut nulla nec dolor venenatis aliquet nec sit amet diam.

Integer euismod, libero vitae malesuada varius, enim mi pharetra nulla, ut lobortis dolor lorem at leo. Vivamus rutrum euismod mi, ut lobortis erat pretium vel. In posuere sapien eu gravida convallis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam finibus urna et nulla imperdiet efficitur. Donec in velit et velit faucibus congue. Cras hendrerit scelerisque libero pretium cursus. Aenean eu nibh velit. Nulla tristique venenatis risus consequat viverra. Donec posuere ultrices scelerisque.

Cras eget euismod eros, et laoreet nisi. Aenean viverra nulla a nisi maximus dictum. Nullam vehicula velit sem, a viverra nisl tristique ut. Vestibulum in odio elit. Mauris et ligula urna. Quisque at enim a dolor pellentesque aliquet. Quisque placerat interdum venenatis.

In hac habitasse platea dictumst. Fusce vehicula nisl ac lectus convallis, in condimentum elit auctor. Fusce convallis orci ante, sit amet gravida orci dapibus nec. Sed elementum suscipit nisi et volutpat. Aenean mollis venenatis sollicitudin. Quisque erat erat, malesuada ac tellus at, pellentesque viverra lacus. Curabitur ornare odio sit amet egestas mollis. Fusce tempus, orci ac rutrum sodales, libero dolor eleifend risus, sed fermentum sapien ipsum vel metus. Praesent vitae diam sapien. Suspendisse malesuada egestas est eget vestibulum. Etiam nec hendrerit est, vel viverra ante. Mauris eget nibh sed massa pellentesque bibendum.

Cras varius purus eu enim maximus venenatis. Nam posuere orci quis enim interdum, et porttitor dolor viverra. Suspendisse sit amet finibus leo, nec blandit augue. Nullam sed mollis diam, at venenatis enim. Curabitur fermentum nisi eu dignissim ultrices. In hac habitasse platea dictumst. Nulla eu facilisis risus, vitae hendrerit lectus. Praesent sem tortor, mattis non felis in, vehicula condimentum nisi.

Aliquam eu facilisis neque. In hac habitasse platea dictumst. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus non feugiat odio, id mollis mauris. Curabitur rhoncus efficitur velit sed pretium. Morbi ut odio quis libero finibus fringilla at vel tortor. Maecenas eget eros pharetra, imperdiet sapien a, suscipit leo. Integer quis convallis elit, eget porttitor urna. Ut imperdiet ligula leo, ac dapibus augue mattis sed.

Donec sit amet nibh elementum, fermentum lectus ut, rhoncus risus. Duis a egestas nunc. Vestibulum eleifend semper turpis at imperdiet. Duis a odio elit. Ut ullamcorper quis ex eget vestibulum. Aenean sit amet magna in est sodales egestas. Maecenas quis diam nec est maximus iaculis ac quis odio. Nunc eget dui ligula.

Phasellus mauris tellus, lacinia ut augue at, tempus hendrerit quam. Ut et leo luctus, feugiat arcu non, fermentum nisi. Nulla velit neque, faucibus quis aliquet a, dapibus et ex. Donec mollis odio vel arcu scelerisque interdum. Vivamus vulputate sed arcu tincidunt suscipit. Integer enim ligula, lobortis a hendrerit quis, mollis at sem. Phasellus pretium nunc ipsum, a tristique est viverra at. Ut tincidunt ligula sed tellus luctus facilisis. In a mi enim. Phasellus imperdiet enim enim, vel gravida quam luctus vitae. Proin at sapien gravida, euismod eros sed, placerat orci.

Phasellus nec pretium justo. Praesent nec euismod nunc. Aliquam fringilla ipsum at tortor egestas, vel pharetra nunc rutrum. Duis quis imperdiet dolor. Cras sit amet est enim. Donec mattis elementum ante, non mollis mauris facilisis sed. Vivamus faucibus, massa ut convallis tempor, nisl elit tristique ante, vel mattis turpis eros finibus ante.

Integer vel libero odio. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris lobortis ex id facilisis rutrum. Etiam elementum orci fermentum, efficitur nisi id, tincidunt velit. Pellentesque ut posuere urna. Nulla in lobortis nisl. Praesent eget ex tortor. Nunc egestas, enim placerat pretium rutrum, massa nulla ultricies leo, ut faucibus urna neque at turpis. Fusce blandit eros non sollicitudin eleifend. Integer est eros, bibendum sollicitudin urna eleifend, porta fermentum enim.

Integer feugiat, ligula vitae sodales posuere, orci sem suscipit lacus, quis consequat metus lorem eu urna. Fusce quis arcu auctor, lobortis nunc eu, venenatis leo. Proin efficitur erat ut nunc consectetur molestie. Quisque lacinia dapibus gravida. In facilisis ligula a dui finibus tincidunt. In consectetur eleifend nulla, nec commodo dui aliquet in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque sed arcu ipsum. Integer pharetra est ut augue cursus tristique. In dapibus vulputate laoreet. Fusce tincidunt vitae nunc vel consectetur. Phasellus velit nunc, ornare ac scelerisque et, fermentum ut purus. Ut lacus dolor, dictum eget congue venenatis, cursus in purus. Donec sodales placerat quam nec viverra.

Maecenas iaculis, dolor nec hendrerit pharetra, nibh neque lacinia massa, eu scelerisque lacus arcu vitae metus. Donec a nisi quis sapien faucibus imperdiet vitae sit amet libero. Nulla laoreet ex metus, ut suscipit nulla convallis eget. Fusce ac quam non erat posuere posuere eget non magna. Fusce nec fermentum felis, nec mattis arcu. Praesent congue mauris orci, nec accumsan lorem tempor eu. Sed ornare nulla ligula, eget suscipit massa eleifend vitae. Fusce eget metus massa. Sed in nulla ac est mattis pulvinar. Suspendisse potenti.

Maecenas vitae sapien lacinia, interdum dolor ac, laoreet lacus. Ut blandit interdum tellus et aliquet. Integer eget orci nec sapien eleifend aliquet. Fusce sollicitudin a nisi luctus facilisis. Donec id purus molestie nibh rutrum dignissim quis ac leo. Quisque malesuada bibendum felis, ut consectetur felis sodales id. Etiam auctor felis at massa bibendum, in fermentum arcu vehicula. Duis fermentum, tortor condimentum convallis porttitor, ante libero aliquet sapien, in aliquet ligula purus ut est.

Phasellus nec enim blandit, cursus nisi quis, dictum sem. Donec eu ligula dolor. Nam tempor porttitor ante, at consequat risus elementum ut. Morbi sed felis vitae diam varius tempus vitae quis nibh. Maecenas pellentesque turpis nibh. Vivamus eget pellentesque justo. Nulla interdum tellus vitae urna venenatis luctus. Donec tincidunt risus vitae ornare sodales. Donec varius mauris eget tellus bibendum, non euismod magna consequat. Aenean tincidunt at mauris ac auctor. Cras pharetra velit lectus, vitae aliquet magna euismod eget.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac nulla eu diam rutrum imperdiet. Vestibulum faucibus ultricies diam, sit amet hendrerit urna tincidunt id. Praesent pulvinar felis sit amet velit hendrerit, in pharetra turpis facilisis. Nam semper suscipit justo, in interdum mi vulputate et. Nulla pharetra porttitor dui, nec ornare neque hendrerit nec. Donec sollicitudin turpis ut sapien condimentum pharetra. Aenean at fringilla tellus. Sed dapibus quam pulvinar, maximus libero at, egestas sapien. Sed sed posuere leo. Cras id metus rhoncus, pharetra tellus ac, posuere quam. Nulla vitae purus lacinia, efficitur eros et, feugiat erat. In quis posuere dolor. Proin pellentesque dolor et purus pretium, sed tincidunt purus blandit. Nullam malesuada, nisl imperdiet lobortis venenatis, erat massa porttitor metus, non imperdiet dui sapien ut sem.

Mauris ut lacinia purus. Nullam libero sapien, suscipit id nibh in, elementum scelerisque ante. Praesent sodales sit amet dolor et imperdiet. Nam nec mauris tempor, viverra urna nec, lobortis est. Ut malesuada, tellus eleifend posuere faucibus, lacus felis molestie metus, quis sodales risus nunc in ante. Etiam ullamcorper dignissim mauris, vel commodo dolor. Ut eleifend luctus sem, a placerat dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Nulla dapibus lacinia eros, id pellentesque ex condimentum at. Sed id tincidunt velit, sed faucibus orci. Phasellus ultricies efficitur sem vehicula mollis. Nunc iaculis, tortor non tempus tincidunt, nibh odio tincidunt dui, elementum laoreet mi urna ac quam. Maecenas commodo ligula in egestas convallis. Sed eleifend commodo orci, ut facilisis turpis auctor sit amet. Pellentesque sed ipsum elit. Curabitur ut eros magna. Integer lorem velit, bibendum eu tempor vitae, mollis id neque. Vestibulum porta aliquet ultricies. Fusce ut ipsum efficitur, gravida orci at, eleifend nisi. Phasellus at tincidunt diam, quis laoreet ligula. Aenean rutrum placerat justo, non suscipit sem convallis eget. Phasellus ut dui vitae diam auctor imperdiet. Mauris ac maximus justo, at consequat mauris. Vivamus sit amet lobortis enim.

Praesent leo orci, malesuada quis nulla non, mollis eleifend tellus. Aliquam accumsan lobortis sem nec luctus. Morbi fermentum, est vitae lacinia tristique, eros dui venenatis orci, vitae mollis urna enim sit amet odio. Integer sit amet bibendum velit. Nam vehicula quis purus a convallis. Quisque blandit, nunc non luctus vestibulum, sapien erat mattis orci, quis mattis velit ante at quam. Suspendisse lorem magna, volutpat quis sodales sit amet, ultrices ac enim.

In tellus justo, congue molestie dolor ut, ultrices euismod nunc. Integer a bibendum nisl. Suspendisse dui mi, ornare eget ullamcorper sed, fringilla pellentesque risus. Vestibulum tempus ipsum vitae velit tempor elementum. In hac habitasse platea dictumst. Quisque nec neque eu nibh malesuada venenatis eget vel arcu. Nulla ut eleifend odio, sit amet aliquam tortor. Nulla rutrum felis augue, at bibendum diam efficitur nec. In sed scelerisque nisi, vulputate vulputate neque. Vivamus commodo viverra malesuada. Donec non est convallis, iaculis turpis ut, blandit neque. Quisque placerat, purus in interdum fringilla, felis mi faucibus mauris, quis semper nulla risus sed urna. Praesent turpis velit, interdum id fringilla blandit, tristique ac sem. Nullam sagittis justo eget feugiat lacinia. In hac habitasse platea dictumst. Duis eget convallis purus.

Vivamus pellentesque, mi eu sagittis placerat, lacus mauris accumsan quam, sed lacinia dolor augue non lectus. Integer justo ex, scelerisque vel viverra non, rhoncus id justo. Phasellus porttitor tristique neque, et ultricies nisl pretium sed. Nullam et blandit erat. Vestibulum et rutrum elit. Aenean metus libero, laoreet ac sem nec, fermentum tristique lacus. Nullam iaculis, neque ut lobortis commodo, felis turpis tempus nulla, eu fermentum neque lectus eget lorem. Donec nulla sem, rutrum in odio tristique, mollis porttitor arcu. Curabitur ac nulla at ipsum maximus pellentesque. Pellentesque eget libero a urna tristique auctor. Quisque porta velit at fermentum hendrerit. Aliquam euismod odio id cursus imperdiet. Sed aliquam vulputate sem id auctor.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis sollicitudin tortor eget congue sagittis. Aliquam congue ut risus at euismod. Pellentesque vehicula ultricies ipsum ut consequat. Sed dictum fringilla ipsum, at tincidunt nulla congue eu. Nulla facilisi. Proin tempor porttitor ligula at placerat. Aliquam tristique venenatis massa ac elementum. Nunc congue consectetur nulla. Cras blandit eget justo in vestibulum. Nunc at pulvinar velit, in volutpat purus. Ut eget erat a nunc volutpat tempus.

Aenean scelerisque sollicitudin pretium. Maecenas vitae dolor metus. Nunc in mi leo. Vivamus a felis non purus ultricies tincidunt. Proin pellentesque ante sem, auctor malesuada sapien ultrices vel. Etiam vestibulum purus mauris, ut consectetur neque tempor in. Fusce quis metus nibh.

Donec mattis suscipit nunc, non sodales mi consequat sed. Quisque gravida mattis justo, sed sodales sem. Nam suscipit venenatis magna, sed commodo est faucibus vitae. In et egestas ligula. Donec sed accumsan ipsum, id dictum nibh. Ut euismod, orci in vehicula sollicitudin, felis risus semper augue, non viverra leo ex ut ligula. Curabitur ac est arcu. Vivamus porttitor dui nec scelerisque feugiat. Nunc eu sodales ante. Nulla neque enim, ornare id pellentesque vel, vulputate non urna. Maecenas arcu urna, condimentum congue placerat eleifend, congue non lectus.

Aliquam non pulvinar sapien. Maecenas sit amet lobortis est. Nulla id nunc commodo, commodo est sit amet, ultrices est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget ex velit. Fusce vitae risus quam. Vestibulum dui nunc, eleifend vitae magna vitae, eleifend lacinia elit. Nulla sodales ut risus non faucibus. Ut suscipit velit in faucibus ultrices.

Donec tempus hendrerit sollicitudin. Ut in accumsan purus. Nam urna augue, tristique in sem consectetur, pulvinar tincidunt tellus. Donec lobortis, purus in efficitur tempor, nunc elit faucibus sapien, eget porta ligula purus sit amet justo. Integer eleifend ac dui laoreet iaculis. Ut consectetur venenatis turpis eget consectetur. Sed libero ligula, sollicitudin non purus vitae, condimentum gravida quam. Sed mauris quam, mollis vitae consequat a, posuere nec ante. Nunc eu mauris sit amet tellus sagittis tempor sit amet vel elit. Morbi suscipit laoreet iaculis.

Aliquam molestie felis vitae dolor congue fermentum quis quis ex. Sed dapibus consequat imperdiet. Suspendisse tincidunt lorem eget nisi molestie sollicitudin. Nunc pretium rutrum est, sit amet dapibus quam semper sit amet. Phasellus nec eros eget velit gravida consectetur. Vivamus commodo metus lobortis lectus auctor, et ornare leo pharetra. Integer vehicula lacus vel enim pretium, a interdum magna aliquam. Sed condimentum purus non diam molestie semper. Nunc urna lectus, euismod nec nisl nec, interdum congue est. Nam ultrices nibh et ex eleifend vestibulum. Morbi lobortis dolor mauris, et maximus massa sollicitudin quis. Integer porta, felis ultricies euismod hendrerit, ligula enim convallis risus, eget elementum nisi augue eget nunc. Phasellus quis facilisis elit. Aliquam condimentum ullamcorper nibh, quis aliquam leo sodales vitae. Nunc varius accumsan justo, eu cursus mauris tincidunt vitae.</div>
    </main>

    <div class="container-fluid">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <p class="col-md-4 mb-0 text-muted">© 2022 Isotrop</p>

            <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-controller" viewBox="0 0 16 16">
                    <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1v-1z" />
                    <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729c.14.09.266.19.373.297.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466.206.875.34 1.78.364 2.606.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527-1.627 0-2.496.723-3.224 1.527-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.34 2.34 0 0 1 .433-.335.504.504 0 0 1-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a13.748 13.748 0 0 0-.748 2.295 12.351 12.351 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.354 12.354 0 0 0-.339-2.406 13.753 13.753 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27-1.036 0-2.063.091-2.913.27z" />
                </svg>
            </a>

            <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            </ul>
        </footer>
    </div>

</body>

</html>